### ISSUE TITLE
Are you practise ASDK in swift？

### ISSUE THREAD

**Issue by wy19901227** [petrpavlik/AsyncChat#1]
![649abcb1-7bd6-4239-bfa7-d9e287273e96](https://cloud.githubusercontent.com/assets/8086633/10778345/21026bfc-7d60-11e5-8e24-505ef967e57a.png)
ASDK is oc ,How did become swift kit?

**Comment by petrpavlik** [comment]
You can build cocoapods as dynamic frameworks using `use_frameworks!` Dynamic frameworks can be imported in Swift without using the bridging header.

**Comment by wy19901227** [comment]
get it

发自我的 iPhone

**Comment by wy19901227** [comment]
evrey cocoopods framework can be use like this, or just some support it?

**Comment by petrpavlik** [comment]
Every pod can beused like this as far as I know.
